import type { SkillType } from "../types";

export const listLength = 12;

export const skills: SkillType[] = [
  { id: 1, name: "ViteJS", variant: "FRONTEND" },
  { id: 2, name: "NextJS", variant: "FRONTEND" },
  { id: 3, name: "React", variant: "FRONTEND" },
  { id: 4, name: "HTML", variant: "FRONTEND" },
  { id: 5, name: "CSS", variant: "FRONTEND" },
  { id: 6, name: "JavaScript", variant: "FRONTEND" },
  { id: 7, name: "TypeScript", variant: "FRONTEND" },
  {
    id: 8,
    name: "TailwindCSS",
    variant: "FRONTEND",
  },
  {
    id: 9,
    name: "StyledComponents",
    variant: "FRONTEND",
  },
  { id: 10, name: "ShadcnUI", variant: "FRONTEND" },
  { id: 11, name: "RadixUI", variant: "FRONTEND" },
  {
    id: 12,
    name: "MaterialUI",
    variant: "FRONTEND",
  },
  {
    id: 13,
    name: "Redux Tool Kit",
    variant: "FRONTEND",
  },
  {
    id: 14,
    name: "React Query",
    variant: "FRONTEND",
  },
  { id: 15, name: "Jotai", variant: "FRONTEND" },
  { id: 16, name: "Zustand", variant: "FRONTEND" },
  {
    id: 17,
    name: "Tanstack Router",
    variant: "FRONTEND",
  },
  {
    id: 18,
    name: "React Router",
    variant: "FRONTEND",
  },
  {
    id: 19,
    name: "Next Router",
    variant: "FRONTEND",
  },
  { id: 20, name: "Axios", variant: "FRONTEND" },
  { id: 21, name: "REST API", variant: "FRONTEND" },
  { id: 22, name: "GraphQL", variant: "FRONTEND" },
  {
    id: 23,
    name: "WebSockets",
    variant: "FRONTEND",
  },
  {
    id: 24,
    name: "SSG, SSR, ISR",
    variant: "FRONTEND",
  },
  {
    id: 25,
    name: "React Hook Form",
    variant: "FRONTEND",
  },
  { id: 26, name: "Formik", variant: "FRONTEND" },
  { id: 27, name: "Zod", variant: "FRONTEND" },
  { id: 28, name: "Yup", variant: "FRONTEND" },
  {
    id: 29,
    name: "Jest",
    variant: "FRONTEND",
  },
  {
    id: 30,
    name: "React Testing Library",
    variant: "FRONTEND",
  },
  {
    id: 31,
    name: "SEO",
    variant: "FRONTEND",
  },
  {
    id: 32,
    name: "Lighthouse",
    variant: "FRONTEND",
  },
  {
    id: 33,
    name: "Profiler",
    variant: "FRONTEND",
  },
  {
    id: 34,
    name: "FSD",
    variant: "FRONTEND",
  },
  {
    id: 35,
    name: "Telegram Mini Apps",
    variant: "FRONTEND",
  },
  {
    id: 36,
    name: "Telegram Analytics",
    variant: "FRONTEND",
  },
  { id: 37, name: "ExpressJS", variant: "BACKEND" },
  { id: 38, name: "NestJS", variant: "BACKEND" },
  { id: 39, name: "JavaScript", variant: "BACKEND" },
  { id: 40, name: "TypeScript", variant: "BACKEND" },
  { id: 41, name: "REST API", variant: "BACKEND" },
  { id: 42, name: "JWT", variant: "BACKEND" },
  { id: 43, name: "SWAGGER", variant: "BACKEND" },
  { id: 44, name: "AWS S3", variant: "BACKEND" },
  { id: 45, name: "Prisma", variant: "BACKEND" },
  { id: 46, name: "Postgres", variant: "BACKEND" },
  { id: 47, name: "Nodemailer", variant: "BACKEND" },
  { id: 48, name: "CORS", variant: "BACKEND" },
  { id: 49, name: "GitHub Actions", variant: "DEVOPS" },
  { id: 50, name: "CI/CD Pipelines", variant: "DEVOPS" },
  { id: 51, name: "Docker", variant: "DEVOPS" },
  {
    id: 52,
    name: "Docker Compose",
    variant: "DEVOPS",
  },
  { id: 53, name: "Nginx", variant: "DEVOPS" },
  { id: 54, name: "Traefik", variant: "DEVOPS" },
  { id: 55, name: "HTTPS", variant: "DEVOPS" },
  { id: 56, name: "VPS", variant: "DEVOPS" },
  {
    id: 57,
    name: "GitHub",
    variant: "TOOLS",
  },
  {
    id: 58,
    name: "GitLab",
    variant: "TOOLS",
  },
  { id: 59, name: "Prettier", variant: "TOOLS" },
  { id: 60, name: "ESlint", variant: "TOOLS" },
  { id: 61, name: "Husky", variant: "TOOLS" },
  { id: 62, name: "Biome", variant: "TOOLS" },
  { id: 63, name: "Jira", variant: "TOOLS" },
  { id: 64, name: "Confluence", variant: "TOOLS" },
  { id: 65, name: "Miro", variant: "TOOLS" },
  { id: 66, name: "Figma", variant: "TOOLS" },
  { id: 67, name: "VSCode", variant: "TOOLS" },
  { id: 68, name: "Scrum", variant: "TOOLS" },
  { id: 69, name: "Kanban", variant: "TOOLS" },
  {
    id: 70,
    name: "NPM",
    variant: "TOOLS",
  },
  {
    id: 71,
    name: "Yarn",
    variant: "TOOLS",
  },
];
